### ISSUE TITLE
Please run the action to build new version 

### ISSUE THREAD

**Issue by lorenc-tomasz** [chiragramani/FlipperReleases#2]

**Comment by chiragramani** [comment]
Apologies, I missed looking into this issue. Just ran the workflow and the releases are updated - https://github.com/chiragramani/FlipperReleases/releases/tag/0.182.0. Thanks!

**Comment by lorenc-tomasz** [comment]
Thank you

**Comment by harshal-moneylion** [comment]
@chiragramani can you run again?

**Comment by chiragramani** [comment]
Thank you @harshal-moneylion, the releases are all updated now. https://github.com/chiragramani/FlipperReleases/releases

**Comment by harshal-moneylion** [comment]
Awesome thanks @chiragramani .
i wonder if it can be automated by listening  to the main flipper repo releases

**Comment by harshal-moneylion** [comment]
@chiragramani is it possible to allow anyone trigger the action? so that you dont have to run your self every time? someone from community can also run it?

**Comment by lorenc-tomasz** [comment]
I have downloaded the repo and run the script by myself locally :)
