### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by markholland** [chiragramani/FlipperReleases#3]
Thanks for providing this repo. It's been great to be able to run Flipper natively on Apple Silicon.

I've been running the action on my own fork but it started failing with `/bin/sh: tsc: command not found` and I can see the last run here had the same problem.

Any idea on what it might be? I tried adding Typescript during the build but then it fails from lots of missing type declarations.

**Comment by cristiano-linvix** [comment]
Same issue here

**Comment by markholland** [comment]
Working again on my side with no changes needed so must have been an upstream issue.
